<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Follow;
use AppBundle\Entity\User;

/**
 * DayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FollowRepository extends \Doctrine\ORM\EntityRepository
{
    public function getFollowedByUser($userId)
    {
        return $this->createQueryBuilder('f')
            ->andWhere('f.fan = :user')
            ->setParameter('user', $this->getEntityManager()->getReference(User::class, $userId))
            ->getQuery()
            ->getResult();
    }

    public function getFollowersByUser($groupId)
    {
        return $this->createQueryBuilder('f')
            ->where('f.group = :group')
            ->setParameter('group', $this->getEntityManager()->getReference(User::class, $groupId))
            ->getQuery()
            ->getResult();
    }
}
