<?php

namespace AppBundle\Repository;

/**
 * GroupSocialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupSocialRepository extends \Doctrine\ORM\EntityRepository
{
}
