<?php

namespace AppBundle\Repository;
use AppBundle\Entity\GroupNews;
use AppBundle\Entity\User;

/**
 * GroupNewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupNewsRepository extends \Doctrine\ORM\EntityRepository
{
    public function deleteAll(User $user)
    {
        $resultSet = $this->createQueryBuilder('gn')
            ->where('gn.group = :user')
            ->setParameter('user', $user)
            ->getQuery()->getResult();

        $em = $this->getEntityManager();
        array_walk(
            $resultSet,
            function (GroupNews $groupNews) use ($em) {
                $em->remove($groupNews);
            }
        );
        $em->flush();
    }
}
