<?php

namespace AppBundle\Repository;

/**
 * GroupTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupTokenRepository extends \Doctrine\ORM\EntityRepository
{
}
