<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    const LEV_THRESHOLD = 50;

    public function search($groupName)
    {
        return $this->createQueryBuilder('u')
            ->where('levenshtein_ratio(u.keyUrl, :groupNameLong) > :LEV_THRESHOLD')
            ->andWhere('u.keyUrl is not null')
            ->setParameter('groupNameLong', $groupName)
            ->setParameter('LEV_THRESHOLD', self::LEV_THRESHOLD)
            ->getQuery()
            ->getResult();
    }

    public function getGroupByUrl($keyUrl)
    {
        $qb = $this->createQueryBuilder('u');
        return $qb->where(
                $qb->expr()->eq("replace(u.groupNameLong,' ','-')", ':keyurl')
            )
            ->setParameter('keyurl', $keyUrl)
            ->getQuery()
            ->getSingleResult();
    }
}
