security:
  encoders:
      FOS\UserBundle\Model\UserInterface: bcrypt

  role_hierarchy:
      ROLE_FAN:         ROLE_USER
      ROLE_GROUP:       ROLE_FAN
      ROLE_FESTIVAL:    ROLE_GROUP
      ROLE_STANDER:     ROLE_FESTIVAL
      ROLE_ADMIN:       ROLE_GROUP
      ROLE_SUPER_ADMIN: ROLE_ADMIN

  providers:
      fos_userbundle:
          id: fos_user.user_provider.username

  firewalls:
      main:
          pattern: ^/
          form_login:
              provider: fos_userbundle
              csrf_token_generator: security.csrf.token_manager
          logout:       true
          anonymous:    true

  access_control:
      - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/admin/, role: ROLE_ADMIN }
      #- { path: ^/events/, role: ROLE_GROUP }